server:
  port: 8888
management:
  security:
    enabled: false
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fredlo2010/pluralsight
          search-paths:
          - '/java-microservices-with-spring-could-developing-services/springcloud-m2-configserver-git/repo/github-pluralsight-spring-cloudconfig-wa-tolls*\*'